spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: render
  datasource:
    url: jdbc:postgresql://localhost:5433/render
    username: postgres
    password: 1111
  application:
    name: app
  cloud:
    gcp:
      storage:
        enabled: true
      project-id: silken-binder-358911
      credentials:
        location: classpath:creds.json

job-distribution:
  framesPerUnit: 10