spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: render
  datasource:
    url: jdbc:postgresql://localhost:5433/render
    username: postgres
    password: 1111
  application:
    name: app
  cloud:
    gcp:
      storage:
        enabled: false
#      project-id: gaimin2020
#      credentials:
#        location: classpath:gaimin-backend-gcp-service-acc-key.json

